import Head from 'next/head'
import Link from 'next/link'

export default function Home({ surahList }) {
  return (
    <>
      <Head>
        <title>E-Quran - Al-Quran Online Lengkap dengan Latin, Audio, Terjemahan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-screen-md mx-auto">
        <div className="flex flex-col divide-y">
          {surahList.map((surah) => (
            <Link key={surah.number} href={"/surah/" + surah.number}>
              <a className="flex flex-row justify-between p-4 hover:bg-gray-100 focus:bg-gray-200">
                <div>
                  <span className="font-bold text-gray-400">{surah.number}.</span> {surah.name.transliteration.id}
                </div>
                <div dir="rtl">{surah.name.short}</div>
              </a>
            </Link>
          ))}
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const req = await fetch('https://api.quran.sutanlab.id/surah')
  const surahList = (await req.json()).data
  
  return {
    props: {
      surahList
    }
  }
}