import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Container from '@/components/Container'
import JadwalShalat from '@/components/JadwalShalat'
import JadwalShalatLoading from '@/components/JadwalShalatLoading'
import GridMenu from '@/components/GridMenu'
import GridMenuItem from '@/components/GridMenuItem'
import { useState, useEffect } from 'react'

const today = new Date()
const DATE = today.getDate()
const MONTH = today.getMonth()
const YEAR = today.getFullYear()

export async function getStaticProps() {
  const req = await fetch('https://api.myquran.com/v1/sholat/kota/semua')
  const res = await req.json()
  const kota = res.filter(kota => {
    return kota.lokasi.startsWith('KOTA')
  }).map(kota => {
    return {
      id: kota.id,
      name: kota.lokasi.replace('KOTA ', '')
    }
  })
  return {
    props: {
      daftarKota: kota
    }
  }
}

export default function Home({ daftarKota }) {
  const [jadwalShalat, setJadwalShalat] = useState(null)
  const [kotaId, setKotaId] = useState(1504)
  
  useEffect(() => {
    fetchJadwal(kotaId)
    async function fetchJadwal(KOTA_ID) {
      const BASE_URL = 'https://api.myquran.com/v1/sholat'
      const req = await fetch(`${BASE_URL}/jadwal/${KOTA_ID}/${YEAR}/${MONTH+1}/${DATE}`)
      const res = await req.json()
      const jadwal = Object.entries(res.data.jadwal)
      setJadwalShalat(jadwal.slice(1,9))
    }
  }, [kotaId])
  
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      { jadwalShalat ? (
        <JadwalShalat 
          onChange={(event) => setKotaId(event.target.value)}
          wilayah={daftarKota}
          date={{DATE, MONTH, YEAR}}
          data={jadwalShalat} />
      ) : (
        <JadwalShalatLoading />
      )}
      
      
      <GridMenu>
        <GridMenuItem href="/quran" icon="quran.png">Al Quran</GridMenuItem>
        <GridMenuItem href="/juz-amma" icon="quran.png">Juz Amma</GridMenuItem>
        <GridMenuItem href="/asmaul-husna" icon="allah.png">Asmaul Husna</GridMenuItem>
      </GridMenu>
    </Container>
  )
}
